name: LighthouseCI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Install lhci
        run: yarn add -D @lhci/cli@0.8.x
      - name: Build
        run: yarn build
      - name: Run Lighthouse
        run: lhci autorun
