name: LighthouseCI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Install dependencies
        run: pnpm install
      - name: Install lhci
        run: pnpm add -D @lhci/cli@0.8.x
      - name: Build
        run: pnpm run build
        env:
          urlPrefix: ''
      - name: Run Lighthouse
        run: pnpm lhci autorun
