name: LighthouseCI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Install lhci
        run: yarn add -D @lhci/cli@0.8.x
      - name: Build
        run: yarn build
        env:
          urlPrefix: ''
      - name: Run Lighthouse
        run: yarn lhci autorun
